query AllSeriesFull(
  $filter: SeriesFilter
  $first: Int
  $orderBy: SeriesOrderBy!
  $orderDirection: OrderDirection!
) {
  allSeries(
    filter: $filter
    first: $first
    orderBy: $orderBy
    orderDirection: $orderDirection
  ) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        type
        private
        workflowStatus
        startTimeScheduled
        updatedAt
        format {
          id
          name
          nameShortened
        }
        title {
          id
          name
          nameShortened
          logoUrl
          private
        }
        tournament {
          id
          name
          nameShortened
          logoUrl
          startDate
          endDate
          venueType
          private
          updatedAt
          prizePool {
            amount
          }
          parent {
            id
            name
          }
          children {
            id
            name
          }
          teams {
            id
            name
          }
          titles {
            id
            name
          }
          externalLinks {
            dataProvider {
              name
              description
            }
            externalEntity {
              id
            }
          }
        }
        teams {
          scoreAdvantage
          baseInfo {
            id
            name
            nameShortened
            logoUrl
            colorPrimary
            colorSecondary
            rating
            private
            updatedAt
            workflowStatus
            organization {
              id
              name
            }
            assets {
              assetType
              url
            }
            title {
              id
              name
            }
            titles {
              id
              name
            }
            externalLinks {
              dataProvider {
                name
                description
              }
              externalEntity {
                id
              }
            }
          }
        }
        players {
          id
          nickname
          fullName
          age
          imageUrl
          private
          updatedAt
          nationality {
            code
            name
          }
          roles {
            id
            name
            private
          }
          team {
            id
            name
          }
          title {
            id
            name
          }
          externalLinks {
            dataProvider {
              name
              description
            }
            externalEntity {
              id
            }
          }
        }
        productServiceLevels {
          productName
          serviceLevel
        }
        streams {
          url
        }
        machineDataSource {
          id
        }
        externalLinks {
          dataProvider {
            name
            description
          }
          externalEntity {
            id
          }
        }
      }
    }
  }
}
