#!/usr/bin/env node
// GRID docs GraphQL CLI. See tools/gql/README.md.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { buildSchema, getVariableValues, Kind } from 'graphql';
import { diffAccess } from './lib/access.js';
import { checkDocument, commercialOnlyUsages } from './lib/check.js';
import { request } from './lib/client.js';
import { accessPath, loadConfig, platformNames, resolveApi, schemaPath, UsageError } from './lib/config.js';
import { getApiKey, redact } from './lib/env.js';
import { introspect } from './lib/introspect.js';
import { countTrimmed, trimLists } from './lib/trim.js';

const USAGE = `Usage: gql <command> [options]

Commands
  introspect <api> [--platform <p>]
      Pull the schema from every platform (or only <p>) and write
      schemas/<api>.graphql (Commercial) and schemas/<api>.<platform>.graphql.
  access <api>
      Diff the stored Commercial and Open Access schemas into
      schemas/<api>.access.json. No API call.
  run <file.graphql> --api <api> [--vars <file.json>] [--platform <p>]
      [--operation <name>] [--trim N] [--out <file>]
      Run a query (Commercial by default) and print or write the response.
      --trim N keeps at most N items in every list; it never changes a value.
  check <file.graphql>... --api <api> [--vars <file.json>] [--platform <p>]
      Validate documents against the stored SDL, offline. With --vars, also
      checks the variable values. Lists Commercial-only usages when
      schemas/<api>.access.json exists.

Each platform has its own API key: GRID_API_KEY (Commercial) and
GRID_OA_API_KEY (Open Access), read from the environment or the gitignored .env
at the repo root. Keys are never accepted as arguments and never printed.

Platforms: ${platformNames().join(', ')}. APIs: ${Object.keys(loadConfig().apis).join(', ')}.`;

const log = (msg) => process.stderr.write(redact(`gql: ${msg}`) + '\n');
const rel = (p) => relative(process.cwd(), p) || p;

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function readJson(path, what) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (err) {
    throw new UsageError(`Cannot read ${what} ${path}: ${err.message}`);
  }
}

function loadSchema(api, platform) {
  const path = schemaPath(api, platform);
  if (!existsSync(path)) throw new UsageError(`${rel(path)} not found. Run: gql introspect ${api}`);
  return buildSchema(readFileSync(path, 'utf8'));
}

async function cmdIntrospect(positionals, opts) {
  const api = positionals[0];
  const platforms = opts.platform ? [opts.platform] : platformNames();
  // Check every key first, so a missing OA key does not leave only half the schemas refreshed.
  for (const platform of platforms) {
    const e = resolveApi(api, platform);
    getApiKey(e.keyEnv, e.platformLabel);
  }
  for (const platform of platforms) {
    const endpoint = resolveApi(api, platform);
    const { schema, sdl } = await introspect(endpoint, { log });
    const header = `# ${endpoint.name} API schema, ${endpoint.platformLabel} platform (${endpoint.url}).\n# Generated by \`gql introspect ${api}\`. Do not edit by hand.\n\n`;
    const out = schemaPath(api, platform);
    writeFile(out, header + sdl);
    const types = Object.keys(schema.getTypeMap()).filter((n) => !n.startsWith('__')).length;
    const count = (t) => (t ? Object.keys(t.getFields()).length : 0);
    log(`${endpoint.platformLabel}: wrote ${rel(out)} (${types} types, ${count(schema.getQueryType())} queries, ${count(schema.getMutationType())} mutations, ${count(schema.getSubscriptionType())} subscriptions)`);
  }
}

function cmdAccess(positionals) {
  const api = positionals[0];
  resolveApi(api);
  const commercial = loadSchema(api, 'commercial');
  const openAccess = loadSchema(api, 'open-access');
  const result = diffAccess(commercial, openAccess, {
    api,
    platforms: { commercial: resolveApi(api, 'commercial').url, 'open-access': resolveApi(api, 'open-access').url },
  });
  const out = accessPath(api);
  writeFile(out, JSON.stringify(result, null, 2) + '\n');
  const s = result.summary;
  const line = (k) => `${k} ${s[k].both} both / ${s[k]['commercial-only']} Commercial only` + (s[k]['open-access-only'] ? ` / ${s[k]['open-access-only']} OA only (unexpected)` : '');
  log(`wrote ${rel(out)}`);
  for (const k of Object.keys(s)) log(`  ${line(k)}`);
}

async function cmdRun(positionals, opts) {
  const file = positionals[0];
  if (!file) throw new UsageError('Missing <file.graphql>.');
  if (!opts.api) throw new UsageError('Missing --api <api>.');
  const trim = opts.trim === undefined ? undefined : Number(opts.trim);
  if (trim !== undefined && !(Number.isInteger(trim) && trim >= 0)) throw new UsageError('--trim must be a non-negative integer.');
  const endpoint = resolveApi(opts.api, opts.platform);
  const query = readFileSync(file, 'utf8');
  const variables = opts.vars ? readJson(opts.vars, 'variables file') : undefined;
  log(`running ${rel(resolve(file))} on ${endpoint.platformLabel} (${endpoint.url})`);
  const body = await request(endpoint, query, variables, { log, operationName: opts.operation });
  let response = body;
  if (trim !== undefined) {
    const removed = countTrimmed(body, trim);
    response = trimLists(body, trim);
    log(`--trim ${trim}: removed ${removed} list item(s); no value changed`);
  }
  const text = JSON.stringify(response, null, 2) + '\n';
  if (opts.out) {
    writeFile(resolve(opts.out), text);
    log(`wrote ${rel(resolve(opts.out))}`);
  } else {
    process.stdout.write(text);
  }
  if (body.errors?.length) {
    for (const e of body.errors) log(`GraphQL error: ${e.message}`);
    return 1;
  }
  return 0;
}

function cmdCheck(positionals, opts) {
  if (!positionals.length) throw new UsageError('Missing <file.graphql>.');
  if (!opts.api) throw new UsageError('Missing --api <api>.');
  const platform = opts.platform ?? loadConfig().defaults.platform;
  resolveApi(opts.api, platform);
  const schema = loadSchema(opts.api, platform);
  const access = existsSync(accessPath(opts.api)) ? readJson(accessPath(opts.api), 'access file') : null;
  const variables = opts.vars ? readJson(opts.vars, 'variables file') : undefined;
  let failed = 0;
  for (const file of positionals) {
    const name = rel(resolve(file));
    const { doc, errors } = checkDocument(schema, readFileSync(file, 'utf8'), name);
    if (doc && !errors.length && variables) {
      for (const op of doc.definitions.filter((d) => d.kind === Kind.OPERATION_DEFINITION)) {
        const coerced = getVariableValues(schema, op.variableDefinitions ?? [], variables);
        for (const e of coerced.errors ?? []) errors.push(`${name} variables: ${e.message}`);
      }
    }
    if (errors.length) {
      failed++;
      for (const e of errors) process.stdout.write(`error ${e}\n`);
      continue;
    }
    if (access && platform === 'commercial') {
      for (const n of commercialOnlyUsages(schema, doc, access, name)) process.stdout.write(`note  ${n}\n`);
    }
    process.stdout.write(`ok    ${name}\n`);
  }
  return failed ? 1 : 0;
}

async function main(argv) {
  const { values: opts, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      api: { type: 'string' },
      platform: { type: 'string' },
      vars: { type: 'string' },
      operation: { type: 'string' },
      trim: { type: 'string' },
      out: { type: 'string' },
      help: { type: 'boolean', short: 'h' },
    },
  });
  const [command, ...rest] = positionals;
  if (opts.help || !command) {
    process.stdout.write(USAGE + '\n');
    return command || opts.help ? 0 : 2;
  }
  switch (command) {
    case 'introspect': return (await cmdIntrospect(rest, opts)) ?? 0;
    case 'access': return cmdAccess(rest) ?? 0;
    case 'run': return cmdRun(rest, opts);
    case 'check': return cmdCheck(rest, opts);
    default: throw new UsageError(`Unknown command "${command}".`);
  }
}

main(process.argv.slice(2)).then(
  (code) => { process.exitCode = code; },
  (err) => {
    const usage = err instanceof UsageError || String(err.code).startsWith('ERR_PARSE_ARGS');
    log(usage ? `${err.message}\n\n${USAGE}` : err.message);
    process.exitCode = usage ? 2 : 1;
  },
);

